# Generated by Django 5.2.17 on 2026-08-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IvrSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64, unique=True)),
                ('from_number', models.CharField(max_length=20)),
                ('state', models.CharField(default='ASK_TYPE', max_length=32)),
                ('answers', models.JSONField(default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ivr', to='reports.incident')),
            ],
        ),
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_number', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('received_at', models.DateTimeField(db_index=True)),
                ('gateway_id', models.CharField(blank=True, max_length=64)),
                ('parsed', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms', to='reports.incident')),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('gateway_id', 'received_at', 'from_number')},
            },
        ),
    ]
