# Generated by Django 5.2.17 on 2026-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('event', models.CharField(max_length=120)),
                ('severity', models.CharField(max_length=20)),
                ('urgency', models.CharField(blank=True, max_length=20)),
                ('certainty', models.CharField(blank=True, max_length=20)),
                ('polygon', models.JSONField(default=list)),
                ('sent_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('raw_xml', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(default='ANDROID', max_length=10)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
