# Generated by Django 5.2.17 on 2026-08-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('client_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('kind', models.CharField(choices=[('FLOOD', 'Flood'), ('CYCLONE', 'Cyclone'), ('LANDSLIDE', 'Landslide')], max_length=12)),
                ('severity', models.PositiveSmallIntegerField()),
                ('people', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('source', models.CharField(choices=[('APP', 'Mobile app'), ('SMS', 'SMS'), ('IVR', 'IVR call')], default='APP', max_length=4)),
                ('reporter_phone', models.CharField(blank=True, max_length=20)),
                ('cell_id', models.CharField(db_index=True, max_length=24)),
                ('corroborations', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='reports_inc_status_c73484_idx')],
            },
        ),
    ]
