# Generated by Django 5.2.17 on 2026-08-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('radius_km', models.FloatField()),
                ('severity', models.PositiveSmallIntegerField()),
                ('source', models.CharField(choices=[('OPERATOR', 'Marked by operator'), ('CAP', 'From alert feed')], default='OPERATOR', max_length=10)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('eta_min', models.FloatField()),
                ('gain', models.FloatField(default=0.0)),
                ('policy', models.CharField(choices=[('OPTIMIZED', 'Optimised'), ('GREEDY', 'Nearest available'), ('GREEDY_SEVERITY', 'Nearest, severity first')], default='OPTIMIZED', max_length=16)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('DISPATCHED', 'Dispatched'), ('ACCEPTED', 'Accepted by team'), ('EN_ROUTE', 'En route'), ('ON_SCENE', 'On scene'), ('TRANSPORTING', 'Transporting'), ('COMPLETE', 'Complete')], db_index=True, default='PROPOSED', max_length=14)),
                ('rescued_count', models.PositiveIntegerField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reports.incident')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='resources.resource')),
                ('shelter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming', to='resources.shelter')),
            ],
            options={
                'ordering': ['-dispatched_at'],
                'indexes': [models.Index(fields=['policy', 'status'], name='dispatch_as_policy_178aa9_idx')],
            },
        ),
    ]
