# Generated by Django 5.2.17 on 2026-08-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('min_lat', models.FloatField()),
                ('min_lon', models.FloatField()),
                ('max_lat', models.FloatField()),
                ('max_lon', models.FloatField()),
                ('node_count', models.PositiveIntegerField()),
                ('edge_count', models.PositiveIntegerField()),
                ('data', models.BinaryField()),
                ('built_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
