# Generated by Django 5.2.17 on 2026-08-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_roadgraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='origin_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='origin_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
