# Generated by Django 5.2.17 on 2026-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_assignment_origin_lat_assignment_origin_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='leg',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
