# Generated by Django 5.2.17 on 2026-08-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_assignment_leg'),
        ('reports', '0002_alter_incident_source'),
        ('resources', '0003_shelter_kind'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignment',
            name='dispatch_as_policy_178aa9_idx',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='policy',
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='dispatch_as_status_dd1af0_idx'),
        ),
    ]
