# Generated by Django 5.2.17 on 2026-08-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IvrSession',
        ),
    ]
