# Generated by Django 5.2.17 on 2026-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='source',
            field=models.CharField(choices=[('APP', 'Mobile app'), ('SMS', 'SMS')], default='APP', max_length=4),
        ),
    ]
