# Generated by Django 5.2.17 on 2026-08-26 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('kind', models.CharField(choices=[('TEAM', 'Rescue team'), ('BOAT', 'Boat'), ('TRUCK', 'Truck'), ('AMBULANCE', 'Ambulance')], max_length=12)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('capabilities', models.JSONField(default=list)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('speed_kmph', models.FloatField(default=35.0)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('ENROUTE', 'En route'), ('ONSCENE', 'On scene'), ('TRANSPORTING', 'Transporting'), ('OUT_OF_SERVICE', 'Out of service')], db_index=True, default='IDLE', max_length=16)),
                ('free_at', models.DateTimeField(blank=True, null=True)),
                ('base_name', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('capacity', models.PositiveIntegerField()),
                ('occupancy', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('INACCESSIBLE', 'Inaccessible')], default='OPEN', max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(choices=[('KIT', 'Survival kit'), ('WATER', 'Water'), ('FOOD', 'Food'), ('MEDICAL', 'First aid')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='resources.depot')),
            ],
            options={
                'unique_together': {('depot', 'item')},
            },
        ),
    ]
