# Generated by Django 5.2.17 on 2026-08-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='kind',
            field=models.CharField(choices=[('SHELTER', 'Cyclone shelter'), ('HOSPITAL', 'Hospital')], db_index=True, default='SHELTER', max_length=10),
        ),
    ]
